// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsgvj0TJDFcSTbXgrabDUXM149Twsfk_c',
    appId: '1:449537684313:web:cf8f90a8c09dfd71895248',
    messagingSenderId: '449537684313',
    projectId: 'myappauth-8aeba',
    authDomain: 'myappauth-8aeba.firebaseapp.com',
    storageBucket: 'myappauth-8aeba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFtNWBeH3u85CalGO_KIwse9PARTLxxkc',
    appId: '1:449537684313:android:e870224ed416f536895248',
    messagingSenderId: '449537684313',
    projectId: 'myappauth-8aeba',
    storageBucket: 'myappauth-8aeba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoerlIKsKCLrMJSwI3ptRJt7j0HTMOgW4',
    appId: '1:449537684313:ios:55420dd30e0fff3b895248',
    messagingSenderId: '449537684313',
    projectId: 'myappauth-8aeba',
    storageBucket: 'myappauth-8aeba.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoerlIKsKCLrMJSwI3ptRJt7j0HTMOgW4',
    appId: '1:449537684313:ios:f7d0a399de2545d7895248',
    messagingSenderId: '449537684313',
    projectId: 'myappauth-8aeba',
    storageBucket: 'myappauth-8aeba.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
